import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { About as AboutComponent } from "../components/PageContainer/About";
import { Layout } from "src/components/Layout";

const About: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <AboutComponent />
      </Layout>
    </div>
  );
};

export default About;
