// このページはＧraphＱL検証用です
// 完全に移行が終わったら削除します。

import { gql, useQuery } from "@apollo/client";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { Layout } from "src/components/Layout";
import { UseGitHubInfoQuery } from "src/types/githubGraphQL";

import styles from "../styles/Home.module.css";

// const GET_LOCATIONS = gql`
//   query GetLocations {
//     locations {
//       id
//       name
//       description
//       photo
//     }
//   }
//  `;

const GET_LOCATIONS = gql`
  query UseGitHubInfo {
    user(login: "topaoad") {
      name
      url
      repositories(last: 5, orderBy: { field: UPDATED_AT, direction: ASC }) {
        totalCount
        nodes {
          name
          description
          createdAt
          updatedAt
          url
          forkCount
          stargazerCount
          languages(orderBy: { field: SIZE, direction: DESC }, last: 10) {
            totalCount
            totalSize
            edges {
              node {
                id
                name
                color
              }
              size
            }
          }
        }
      }
    }
  }
`;

const Apollotest: NextPage = () => {
  const { data, error, loading } = useQuery<UseGitHubInfoQuery>(
    GET_LOCATIONS
  );

  const dataQL = data?.user?.repositories?.nodes;

  return (
    <div className={styles.container}>
      <Head>
        <title>Apolltest</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>
      <ul>
            {dataQL?.map((dataql, index) => (
              <li key={index} className="mt-6 ">
                <Link href={dataql?.url}>
                  <a>
                    <h3 className="text-2xl font-bold">{dataql?.createdAt}</h3>
                   
                    <p> {dataql?.forkCount}</p>
                    <p> {dataql?.stargazerCount}</p>
                  </a>
                </Link>
              </li>
            ))}
          </ul>
      </Layout>
    </div>
  );
};

export default Apollotest;
