import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { BlogArchive } from "../components/PageContainer/BlogArchive";
import { Layout } from "src/components/Layout";
import { client } from "src/lib/miscrocms/client";

const Blog: NextPage = ({blog}) => {
  return (
    <div className={styles.container}>
      <Head>
      <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>
      <BlogArchive blog={blog}/>
      </Layout>
    </div>
  );
};

export default Blog;
export const getStaticProps = async () => {
  const data = await client.get({ endpoint: "mainblog" });

  return {
    props: {
      blog: data.contents,
    },
  };
};