import type { NextPage } from "next";
import Head from "next/head";
import { Layout } from "src/components/Layout";

import { FormList } from "../components/PageContainer/FormList";
import styles from "../styles/Home.module.css";

const Contact: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>
        <FormList />
      </Layout>
    </div>
  );
};

export default Contact;

