import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { Layout } from "src/components/Layout";
import { client } from "src/lib/miscrocms/client";
import { BlogPortfolioProps } from "src/types/microCmsData";

import { PortFolio } from "../components/PageContainer/PortFolio";
import styles from "../styles/Home.module.css";

const Portfolio: NextPage<BlogPortfolioProps> = (props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>
        <PortFolio portfolio={props.portfolio} />
      </Layout>
    </div>
  );
};

export default Portfolio;

export const getStaticProps: GetStaticProps = async () => {
  // const data = await client.get({ endpoint: "mainblog" });
  const data = await client.get({
    endpoint: "mainblog",
    queries: { limit: 5, offset: 0 },
  });
  const portfolioData = await client.get({
    endpoint: "portfolio",
    queries: { limit: 20, offset: 0 },
  });

  return {
    props: {
      blog: data.contents,
      portfolio: portfolioData.contents,
    },
  };
};
